window.ONLYWORLD_CONTENT = {
  welcome: {
        kicker: "おいおい,こいつは何も知らないバカですよ",
    title: "OnlyWorld's  幻想乡",
        subtitle: "…ようこそ。Ave Mujica の世界へ",
    button: "Start",
  },
  profile: {
      avatar: "assets/Iriyabest.jpg",
    greeting: "OnlyWorld",
    bio: "目前是学生，网络安全专业。不资深的ACG爱好者~~~O……O",
    direction: "Pwn，Web，Re，PUBG，MC,animation",
    topics: "哪有什么主题，就看哪个感兴趣~~",
    status: "loading……-->",
    email: "邮箱：1325636110@qq.com",
    birthday: "7.21",
      github: "https://github.com/Roxygod258",
    website: "codex大人随手赏赐我的罢了，仅作个人学习和记录~~",
      belief: "Roxy and Iriya are both my dearst beloveds. ♥",
  },
  photos: [],
  music: {
      title: "蝶に結いた赤い糸",
      artist: "トゲナシトゲアリ",
    src: "assets/トゲナシトゲアリ - 蝶に結いた赤い糸.mp3",
    cover: "assets/ucwc.jpg",
  },
  appearance: {
    wallpaper: "assets/zjcwn.jpg",
    shade: 32,
    blur: 0,
    contentOpacity: 70,
    navOpacity: 88,
    musicVolume: 80,
    sakura: true,
  },
};
